### PR TITLE
Fix: Slurm collector handles ambiguous local time after switching from CEST to CET

### LINKED ISSUE #518: Slurm collector crashes after switch to winter/standard time
```
systemd[1]: Started AUDITOR SLURM collector.
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[SLURM COLLECTOR - START]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.734550119Z","target":"auditor_slurm_collector","line":84,"file":"collectors/slurm/src/main.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766"}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[STARTING SACCT MONITOR - START]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.736869247Z","target":"auditor_slurm_collector::sacctcaller","line":40,"file":"collectors/slurm/src/sacctcaller.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766"}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[STARTING SACCT MONITOR - END]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.736968219Z","target":"auditor_slurm_collector::sacctcaller","line":40,"file":"collectors/slurm/src/sacctcaller.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766","elapsed_milliseconds":0}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[STARTING AUDITORSENDER - START]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.737816231Z","target":"auditor_slurm_collector::auditorsender","line":28,"file":"collectors/slurm/src/auditorsender.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766"}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[STARTING AUDITORSENDER - END]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.737872625Z","target":"auditor_slurm_collector::auditorsender","line":28,"file":"collectors/slurm/src/auditorsender.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766","elapsed_milliseconds":0}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[CALLING SACCT AND PARSING OUTPUT - START]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.738162231Z","target":"auditor_slurm_collector::sacctcaller","line":94,"file":"collectors/slurm/src/sacctcaller.rs"}
Oct 30 09:31:27 auditor-slurm-collector[17165]: thread 'tokio-runtime-worker' panicked at 'Ambiguous local time, ranging from 2023-10-29T02:22:07+01:00 to 2023-10-29T02:22:07+02:00', collectors/slurm/src/database.rs:93:59
Oct 30 09:31:27 auditor-slurm-collector[17165]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[CALLING SACCT AND PARSING OUTPUT - END]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.738773842Z","target":"auditor_slurm_collector::sacctcaller","line":94,"file":"collectors/slurm/src/sacctcaller.rs","elapsed_milliseconds":0}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[SLURM COLLECTOR - EVENT] Shutdown signal from inside application received.","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.738940071Z","target":"auditor_slurm_collector","line":139,"file":"collectors/slurm/src/main.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766"}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[SENDING SHUTDOWN SIGNAL TO SACCTCALLER AND AUDITORSENDER - START]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.738975333Z","target":"auditor_slurm_collector::shutdown","line":50,"file":"collectors/slurm/src/shutdown.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766"}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[SENDING SHUTDOWN SIGNAL TO SACCTCALLER AND AUDITORSENDER - END]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.73906013Z","target":"auditor_slurm_collector::shutdown","line":50,"file":"collectors/slurm/src/shutdown.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766","elapsed_milliseconds":0}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[SLURM COLLECTOR - EVENT] Could not send shutdown signal to tasks: channel closed\n\nLocation:\n    collectors/slurm/src/shutdown.rs:56:13","level":50,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.73913181Z","target":"auditor_slurm_collector","line":144,"file":"collectors/slurm/src/main.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766"}
Oct 30 09:31:27 auditor-slurm-collector[17165]: {"v":0,"name":"AUDITOR-slurm-collector","msg":"[SLURM COLLECTOR - END]","level":30,"hostname":"slurm.bfg.uni-freiburg.de","pid":17165,"time":"2023-10-30T08:31:27.739205015Z","target":"auditor_slurm_collector","line":84,"file":"collectors/slurm/src/main.rs","run_id":"c5762663-b115-4d8d-8e5d-8ea09b30d766","elapsed_milliseconds":4}
systemd[1]: auditor-slurm-collector.service holdoff time over, scheduling restart.
systemd[1]: Stopped AUDITOR SLURM collector.
```

Not sure if related to #249

### PR DESCRIPTION
**Pull request by raghuvar-vijay**
This fixes #518.

Slurm collector crashes when daylight savings ends ( switches from CEST to CET). Due to this change, the timestamp stored in the db differs in timezone compared to the local time. This raises ambiguity while comparing the queried timezone (CEST) and the current local timezone (CET). 

The issue is fixed by choosing the timezone in which the queried timestamp was already saved in the db, which in this case would be CEST.

### CODE REVIEW

File: collectors/slurm/src/database.rs [hunk 1]
```diff
@@ -90,7 +90,23 @@ impl Database {
...
-                Ok((Local.from_local_datetime(&lastcheck).unwrap(), jobid))
+                //Ok((Local.from_local_datetime(&lastcheck).unwrap(), jobid))
+
+                match Local.from_local_datetime(&lastcheck) {
+                    LocalResult::Single(datetime) => Ok((datetime, jobid)),
+                    LocalResult::Ambiguous(datetime1, datetime2) => {
+                        tracing::info!("Ambiguous local time, ranging from t1 = {:?} to t2 = {:?} . Choosing t1 as timestamp", datetime1, datetime2);
+                        Ok((datetime1, jobid))
+                    }
+                    _ => {
```
Comment (QuantumDancer) [inline collectors/slurm/src/database.rs:101]: Instead of using `_` I think it would be better to explicitly match the third case (`chrono::LocalResult::None`), in case there would be additional variants of the enum in the future.

**Review by QuantumDancer — CHANGES_REQUESTED** [review]
Could you please mention the underlying issue in the PR description?

I have one comment regarding the code, see below.

Otherwise, once the changelog has been added, I think this is ready to be merged.

**Review by QuantumDancer — APPROVED** [review]
